# Generated by ChatGPT on 2026-02-02

from django.db import migrations, models


def mark_existing_users_verified(apps, schema_editor):
    """Keep existing installations working: mark currently active users as verified."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(is_active=True).update(is_email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_users_verified, migrations.RunPython.noop),
    ]
