# Generated by Django 5.2.8 on 2025-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='instructor',
            field=models.CharField(help_text='نام/عنوان استاد را وارد کنید', max_length=200),
        ),
    ]
